version: 1

formatters:
  default:
    format: "%(name)-15s %(asctime)s %(levelname)-8s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  fluent_fmt:
    "()": fluent.handler.FluentRecordFormatter
    format:
      level: "%(levelname)s"
      hostname: "%(hostname)s"
      where: "%(module)s.%(funcName)s"
      name: "%(name)s"

  str_fluent_fmt:
    "()": "fluentd_example.formatters.StringFluentRecordFormatter"
    format:
      level: "%(levelname)s"
      hostname: "%(hostname)s"
      where: "%(module)s.%(funcName)s"
      name: "%(name)s.str"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout

  rotating_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: str_fluent_fmt
    filename: app.log
    maxBytes: 8192
    backupCount: 1

  fluent:
    class: fluent.handler.FluentHandler
    host: fluentd
    verbose: True
    port: 24224
    tag: test.logging
    formatter: fluent_fmt
    level: DEBUG

  none:
    class: logging.NullHandler

loggers:
  app:
    handlers: [console, fluent, rotating_file]
    level: DEBUG
    propagate: False

  "app.route":
    handlers: []
    level: DEBUG
    propagate: True

  "app.method":
    handlers: []
    level: DEBUG
    propagate: True

  "app.exception":
    handlers: []
    level: ERROR
    propagate: True

  werkzeug:
    handlers: [console, fluent]
    level: ERROR
    propagate: False

  '':  # root logger
    handlers: [console, fluent]
    level: ERROR
